2023-06-13 14:58:07,425 - ERROR - An unexpected error occurred: invalid literal for int() with base 10: 'None'
Traceback (most recent call last):
  File "/Workshop/challenge_2/main.py", line 126, in <module>
    vent_control(level_value)
  File "/Workshop/challenge_2/main.py", line 68, in vent_control
    ser_vent.write(str(int(str(vent))).encode()) # Wanted voltage for right speed
ValueError: invalid literal for int() with base 10: 'None'
2023-06-13 14:58:29,285 - ERROR - An unexpected error occurred: invalid literal for int() with base 10: 'None'
Traceback (most recent call last):
  File "/Workshop/challenge_2/main.py", line 126, in <module>
    vent_control(level_value)
  File "/Workshop/challenge_2/main.py", line 68, in vent_control
    ser_vent.write(str(int(str(vent))).encode()) # Wanted voltage for right speed
ValueError: invalid literal for int() with base 10: 'None'
2023-06-13 15:01:00,308 - ERROR - An unexpected error occurred: invalid literal for int() with base 10: 'None'
Traceback (most recent call last):
  File "/Workshop/challenge_2/main.py", line 131, in <module>
    vent_control(level_value)
  File "/Workshop/challenge_2/main.py", line 68, in vent_control
    ser_vent.write(str(int(str(vent))).encode()) # Wanted voltage for right speed
ValueError: invalid literal for int() with base 10: 'None'
2023-06-13 15:19:54,450 - ERROR - PostgreSQL database error: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

